### ISSUE TITLE
Adding some usage steps

### ISSUE THREAD

**Issue by userrand** [loiccoyle/base16-sioyek#2]
Thanks this is awesome.

 I am just adding some steps for other users that might not have understood how to use this.
 
 First, it seems to me that it is sufficient to just pick one of the .config color schemes in the colors folder of this repository and then copy-paste the text from that file into your .config/sioyek/prefs_user.config file without having to use git on the entire repository (in particular this makes it easier to avoid any potentially malicious code as is often a problem when bringing a lot of code into one's computer)
 
then, 

 as shown at https://sioyek-documentation.readthedocs.io/en/latest/commands.html#toggle-custom-color

with sioyek open, one can toggle the color of the document using `:` to enter command mode and then enter the command :

`toggle_custom_color`

**Comment by loiccoyle** [comment]
Yep! Thanks for clarifying for newcomers, if you want to make changes to the `README`, feel free to open a PR.

> in particular this makes it easier to avoid any potentially malicious code as is often a problem when bringing a lot of code into one's computer

True, just to clarify, firstly git cloning does not run any code afaik, secondly this repo doesn't contain any code only "text"/configuration files so there would be no code to run in any case.

**Comment by userrand** [comment]
> Yep! Thanks for clarifying for newcomers, if you want to make changes to the `README`, feel free to open a PR.
> 
> > in particular this makes it easier to avoid any potentially malicious code as is often a problem when bringing a lot of code into one's computer
> 
> True, just to clarify, firstly git cloning does not run any code afaik, secondly this repo doesn't contain any code only "text"/configuration files so there would be no code to run in any case.

Hi, my main concern was the automatic .git workflow bot in the repository. I do not know what it is or how it works and so I preferred to stay on the safe side and just copy-paste only what I wanted.

**Comment by loiccoyle** [comment]
FYI: git workflows are automations a repo owner can set up. They run on github's servers not on user's systems.

I'm using them to build the files in the `colors` folder periodically.

See: https://github.com/loiccoyle/base16-sioyek/actions if you're curious.
